### ISSUE TITLE
Failed to set value '/dev/dri/renderD128' for option 'qsv_device': Unknown error occurred

### ISSUE THREAD

**Issue by jmros** [MacRimi/HWEncoderX#1]

**Comment by MacRimi** [comment]
It seems like the error you're experiencing might be related to either using the example Docker Compose file that includes GPU configuration, or it could be because your system doesn't have an NVIDIA GPU.

The Docker Compose file provided is only an example, and it includes the following part:

```
deploy:
  resources:
    reservations:
      devices:
        - capabilities: [gpu]  # For NVIDIA NVENC
```
This configuration is meant for environments with an NVIDIA GPU. If your system does not have an NVIDIA GPU, or if the necessary drivers aren't installed, this will cause an error like the one you encountered.

To resolve this, you can:

Remove or comment out the deploy: section if you do not have an NVIDIA GPU.
If you have an NVIDIA GPU, make sure that the [NVIDIA Container Toolkit](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html) is installed properly.
Here is an updated docker-compose.yml without the deploy: section:

```
version: '3.3'
services:
  hwencoderx:
    image: macrimi/hwencoderx:latest
    container_name: hwencoderx
    restart: unless-stopped
    devices:
      - /dev/dri:/dev/dri  # For VAAPI
    volumes:
      - /path/to/input:/input 
      - /path/to/output:/output 
    environment:
      QUALITY: "18" # Optional
      PRESET: "medium" # Optional
      BOT_TOKEN: "xxxxxxxxxxxxxxxxxxxxxxxxxx" # Optional (replace with your TOKEN, requires CHAT_ID)
      CHAT_ID: "xxxxxxxx" # Optional (replace with your CHAT_ID, requires BOT_TOKEN)
      NOTIFICATIONS: "all" # Optional
```
Please note that this Compose file is just a starting point. You may need to adjust it based on your environment and available hardware.
